# icons.py - Definizioni delle icone per il menù

# Definisci i tuoi colori qui per averli a portata di mano
B = (0, 0, 0)       # Black (spento)
W = (30, 30, 30)    # White
R = (25, 0, 0)      # Red
O = (20, 12, 0)     # Orange
Y = (28, 25, 0)     # Yellow
G = (0, 28, 0)      # Green
J = (0, 10, 0)      # Verde scuro
S = (115, 23, 86)   # Rosa
V = (18, 1, 38)     # Viola
L = (3, 3, 70)      # Blu
F = (0, 0, 20)      # Blu scuro
N = (26, 26, 26)    # Grigio
M = (12, 12, 12)    # Grigio SCURO

# Dizionario che contiene tutte le icone
ICONS = {
    'logo': [
        [S,S,B,B,S,S,S,S,S,S,S,B,B,S,S,S],
        [B,B,S,B,V,B,B,V,B,B,B,S,B,V,B,S],
        [V,V,B,B,V,V,B,V,B,V,V,B,B,V,B,V],
        [V,B,V,B,V,B,B,V,B,V,B,V,B,L,B,V],
        [L,B,L,B,L,L,B,L,B,L,B,L,B,L,L,L],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [S,S,S,B,S,B,S,B,S,B,S,S,S,S,S,B],
        [V,B,B,B,B,B,V,B,V,B,V,B,B,B,B,S],
        [V,V,B,B,V,B,B,V,B,B,V,V,B,V,V,B],
        [V,B,B,B,V,B,V,B,V,B,V,B,B,V,B,V],
        [L,B,B,B,L,B,L,B,L,B,L,L,B,L,B,L],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,L,B,L,L,B,L,L,L,L,B,L,L,B,L,B],
        [B,N,B,N,N,B,N,N,N,N,B,N,N,B,N,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
    ],
        'sub': [
        [B,B,B,B,B,B,B,L,L,B,B,B,B,B,B,B],
        [B,L,L,L,B,L,L,L,L,L,L,B,L,L,L,B],
        [B,B,L,B,L,L,L,L,L,L,L,L,B,L,B,B],
        [L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L],
        [L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L],
        [B,L,L,L,L,L,L,L,L,L,L,L,L,L,L,B],
        [B,B,L,L,L,L,L,L,L,L,L,L,L,L,B,B],
        [F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,F,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,F,F,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,F,F,B,B,B,B,B,B,B,B],
        [B,B,B,F,F,F,F,F,F,F,F,F,F,F,B,F],
        [B,B,F,F,F,F,F,F,F,F,F,F,F,F,F,F],
        [B,B,B,F,F,F,F,F,F,F,F,F,F,F,B,F],
    ],
    'race': [
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,R,R,R,R,R,R,B,B,B,B,B],
        [B,B,B,B,B,B,B,R,R,B,B,B,B,B,B,B],
        [B,B,B,B,M,M,B,R,R,B,M,M,B,B,B,B],
        [B,B,B,B,M,M,B,R,R,B,M,M,B,B,B,B],
        [B,B,B,B,M,M,B,R,R,B,M,M,B,B,B,B],
        [B,B,B,B,B,B,R,R,R,R,B,B,B,B,B,B],
        [B,B,B,B,B,B,R,B,B,R,B,B,B,B,B,B],
        [B,B,B,B,B,B,R,B,B,R,B,B,B,B,B,B],
        [B,B,M,M,B,R,R,W,W,R,R,B,M,M,B,B],
        [B,B,M,M,B,R,R,W,W,R,R,B,M,M,B,B],
        [B,B,M,M,B,R,R,R,R,R,R,B,M,M,B,B],
        [B,B,M,M,B,R,R,R,R,R,R,B,M,M,B,B],
        [B,B,B,B,B,B,B,R,R,B,B,B,B,B,B,B],
        [B,B,B,R,R,R,R,R,R,R,R,R,V,B,B,B],
        [B,B,B,V,V,V,V,V,V,V,V,V,V,B,B,B],
    ],
        'invaders': [
        [B,B,B,B,B,B,V,V,V,B,B,B,B,B,B,B],
        [B,B,B,V,V,V,V,V,V,V,V,V,B,B,B,B],
        [B,B,V,V,V,V,V,V,V,V,V,V,V,B,B,B],
        [B,B,V,V,B,B,V,V,V,B,B,V,V,B,B,B],
        [B,B,V,V,V,V,V,V,V,V,V,V,V,B,B,B],
        [B,B,B,B,V,V,B,B,B,V,V,B,B,B,B,B],
        [B,B,V,V,B,B,V,V,V,B,B,V,V,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [Y,B,Y,Y,Y,W,W,W,W,W,W,Y,Y,Y,B,Y],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,G,J,B,B,B,B,B,B,B],
        [B,B,B,B,G,G,G,G,G,G,J,J,B,B,B,B],
        [B,B,B,G,G,G,G,G,G,G,G,J,J,B,B,B],
        [B,B,B,J,J,J,J,J,J,J,J,J,J,B,B,B],
    ],
        'arkanoid': [
        [O,O,O,O,O,B,O,O,O,O,B,O,O,O,O,O],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [Y,Y,Y,Y,Y,B,Y,Y,Y,Y,B,Y,Y,Y,Y,Y],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,W,W,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,W,W,W,M,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,M,M,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,W,W,R,R,R,R,R,R,R,R,W,W,B,B],
        [B,W,W,W,R,R,R,R,R,R,R,R,W,W,M,B],
        [B,B,M,M,V,V,V,V,V,V,V,V,M,M,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
    ],
        'pacman': [
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,Y,Y,Y,B,B,B,B,B,B,B,B,B],
        [B,B,Y,Y,Y,Y,Y,Y,Y,B,B,B,B,B,B,B],
        [B,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B,B,B,B,B],
        [B,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B,B,B,B,B],
        [Y,Y,Y,Y,Y,Y,Y,B,B,B,B,B,O,O,B,B],
        [Y,Y,Y,Y,B,B,B,B,B,B,B,O,O,O,O,B],
        [Y,Y,Y,Y,Y,Y,Y,B,B,B,B,B,O,O,B,B],
        [B,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B,B,B,B,B],
        [B,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B,B,B,B,B],
        [B,B,Y,Y,Y,Y,Y,Y,Y,B,B,B,B,B,B,B],
        [B,B,B,B,Y,Y,Y,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
    ],
        'pong': [
        [B,B,B,L,L,L,L,B,B,B,B,B,B,B,B,B],
        [B,B,L,L,L,L,L,L,B,B,B,B,B,B,B,B],
        [B,B,L,L,L,L,L,L,W,W,W,B,B,B,B,B],
        [B,B,L,L,L,L,L,L,B,B,B,B,B,B,B,B],
        [B,B,B,L,L,L,L,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,W,W,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,W,W,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,B,B,B,O,O,O,O,B,B],
        [B,B,B,B,B,B,B,B,B,O,O,O,O,O,O,B],
        [B,B,B,B,B,B,W,W,W,O,O,O,O,O,O,B],
        [B,B,B,B,B,B,B,B,B,O,O,O,O,O,O,B],
        [B,B,B,B,B,B,B,B,B,B,O,O,O,O,B,B],
    ],
        'sheriff': [
        [B,B,B,B,B,B,B,W,O,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,O,O,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,Y,Y,B,B,B,B,B,B,B],
        [W,O,B,B,B,B,Y,Y,Y,Y,B,B,B,B,W,O],
        [O,O,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,O,O],
        [B,B,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B],
        [B,B,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B],
        [B,B,B,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B,B],
        [B,B,B,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B,B],
        [B,B,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B],
        [B,B,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,B,B],
        [W,O,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,W,O],
        [O,O,B,B,B,B,Y,Y,Y,Y,B,B,B,B,O,O],
        [B,B,B,B,B,B,B,Y,Y,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,W,O,B,B,B,B,B,B,B],
        [B,B,B,B,B,B,B,O,O,B,B,B,B,B,B,B],
    ]
}